[mypy]
python_version = 3.9
files = src
explicit_package_bases = True
ignore_missing_imports = True
follow_imports = silent
disallow_untyped_defs = True
warn_unused_ignores = False
disable_error_code = assignment,arg-type,attr-defined,has-type,index,name-defined,operator,return,return-value,var-annotated
