import java.io.*;
import java.util.*;
class Main {
// Generated by 1.1.7.1 https://github.com/kyuridenamida/atcoder-tools  (tips: You use the default template now. You can remove this line by using your custom template)
public static void main(String[] args) throws Exception {
final Scanner sc = new Scanner(System.in);
long N;
N = sc.nextLong();
long K;
K = sc.nextLong();
long[] h = new long[(int)(N)];
for(int i = 0 ; i < N ; i++){
h[i] = sc.nextLong();
}
solve(N, K, h);
}
static void solve(long N, long K, long[] h){
long[] dp = new long[(int)(N+1)];
for (int i = 2; i <= N; i++){
long tmp = Integer.MAX_VALUE;
for (int j = 1; j <= K; j++){
if (i - j - 1 >= 0){
tmp = Math.min(tmp, dp[i-j] + Math.abs(h[i-1] -h[i-j-1]));
}
}
dp[i] = tmp;
}
System.out.print(dp[(int)(N)]);
}
}